export enum actionTypes {
  FETCH_ARTWORK = 'FETCH_ARTWORK',
  FETCH_ARTWORK_FULFILLED = 'FETCH_ARTWORK/fulfilled',
  FETCH_ARTWORK_PENDING = 'FETCH_ARTWORK/pending',
  FETCH_ARTWORK_REJECTED = 'FETCH_ARTWORK/rejected',
  FETCH_ARTWORKS = 'FETCH_ARTWORKS',
  FETCH_ARTWORKS_FULFILLED = 'FETCH_ARTWORKS/fulfilled',
  FETCH_ARTWORKS_PENDING = 'FETCH_ARTWORKS/pending',
  FETCH_ARTWORKS_REJECTED = 'FETCH_ARTWORKS/rejected',
  SET_ARTWORKID = 'SET_ARTWORKID',
}
